# Generated by Django 5.0.6 on 2024-06-11 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Adquisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.FloatField()),
                ('adquisition_type', models.CharField(max_length=250)),
                ('quantity', models.IntegerField()),
                ('unit_cost', models.FloatField()),
                ('total_cost', models.FloatField()),
                ('date', models.DateField()),
                ('docs', models.TextField()),
                ('status', models.CharField(choices=[('ENABLED', 'Activada'), ('DISABLED', 'Desactivada')], default='ENABLED', max_length=250)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adquisitions_api.adminunit')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adquisitions_api.supplier')),
            ],
        ),
    ]
