# Generated by Django 5.0.6 on 2024-06-12 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=250, unique=True)),
                ('password', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('middle_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('id_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Acquisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.FloatField()),
                ('acquisition_type', models.CharField(max_length=250)),
                ('quantity', models.IntegerField()),
                ('unit_cost', models.FloatField()),
                ('total_cost', models.FloatField()),
                ('date', models.DateField()),
                ('docs', models.TextField()),
                ('status', models.CharField(choices=[('ENABLED', 'Activada'), ('DISABLED', 'Desactivada'), ('DELETED', 'Eliminada')], default='ENABLED', max_length=250)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acquisition_api.adminunit')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acquisition_api.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('MODIFIED', 'Modificado'), ('CREATED', 'Creado'), ('DELETED', 'Eliminado')], max_length=250)),
                ('date', models.DateTimeField()),
                ('acquisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acquisition_api.acquisition')),
            ],
        ),
    ]
