# Generated by Django 5.0.6 on 2024-06-12 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acquisition_api', '0002_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
    ]
