# Generated by Django 5.0.6 on 2024-06-12 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acquisition_api', '0004_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
